### ISSUE TITLE
Hello, did you get the library file or manual for PAW3370? Is it possible to share?

### ISSUE THREAD

**Issue by youziLab** [perigoso/sungorus#1]
I only have their website, but it seems that the profile page reports error 403.
Hello, did you get the library file or manual for PAW3370? Is it possible to share?
https://www.pixart.com/products-detail/135/PAW3370DM-T4QU

**Comment by perigoso** [comment]
Unfortunately it's "confidential", and I never got access to in depth docs, I worked mostly through reverse engineering.
I do have a product brief here I could send you through email, if you wish.
